### PR TITLE
Summer intership2022 man fra

### PR DESCRIPTION
**Pull request by FranciscoConceicao**
Manuel and I created the Java project for the F4PGAAPI and started developing it.

### CODE REVIEW

**Review by nmcp88 — CHANGES_REQUESTED** [review]
A pasta "f4fpga-examples" é necessária? Parece acrescentar centenas de ficheiros e ser por sua vez um clone de outro repo.

Por favor não ponham repos dentro de repos. No projecto F4PGAAPI só devia constar código original vosso (em principio o "resources/pt/fe/up/f4pga" e o "src/pt/fe/up/f4pga"; eventualmente um "test/pt/fe/up/f4pga" quando quiserem fazer testes unitários.

Se o "f4pga-examples" for uma dependencia (e.g., instalar as ferramentas f4pga) isso é uma dependencia externa que se resolve fora do projecto. Pelo que vejo, as centenas de ficheiros adicionados vem todos dai (e agora ficam já no histórico dos commits, mesmo que se removam agora, i.e., ocupa espaço no repo, em MBs mesmo). 

Movam essa pasta para fora do "specs-hw", se possível.

**Review by joaobispo — COMMENTED** [review]
The folder F4PGA seems to me that it should not be in the repository.

Remember that you only want to commit the minimum necessary code that you developed (e.g. automatically generated code should not be in the repository, if it can be generated during the compilation process), that everything you commit to a repository will be there forever (even if you delete it), and any files that are not ours but that can be found somewhere, should be handled as an external dependency.

We can discuss how to handle this in this case. Meanwhile, @lm-sousa, can you see how to remove this folder so that it does not go to the main branch?

**Comment by nmcp88** [comment]
@joaobispo The folder "F4PGA"? I don't see a folder by that name... do you mean "F4FPGAPI"? That folder is the root of the Eclipse project!

**Comment by joaobispo** [comment]
> @joaobispo The folder "F4PGA"? I don't see a folder by that name... do you mean "F4FPGAPI"? That folder is the root of the Eclipse project!

I meant 'f4pga-examples'

**Pull request closed without merging**
